// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: 7_5_23

#include "ui.h"

void ui_comp_Slider1_create_hook(lv_obj_t * comp)
{
}
